spring.application.name=mediqr-backend

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT Configuration
app.jwt.secret=mediqr-super-secret-jwt-key-change-in-production-min-256-bits-long-enough-for-hs256
app.jwt.expiration=86400000